# FASTLANE_USER="lucasfigueiredo285@gmail.com"
# FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD="dabt-ildz-iesf-gfvb"




# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "appstore")
    increment_build_number(xcodeproj: "UdemyFastlane.xcodeproj")
    build_app(workspace: "UdemyFastlane.xcworkspace", scheme: "UdemyFastlane")
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
    clean_build_artifacts
    commit_version_bump(
      message: "ci: Released new beta build #{lane_context[SharedValues::BUILD_NUMBER]} to TestFlight [ci skip]",
      xcodeproj: "UdemyFastlane.xcodeproj",
      force: true
    )
  end
end
